[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "archcode"
version = "0.1.0"
description = "Reproducible physics-based framework for 3D genome architecture."
requires-python = ">=3.9"
